.github/CODEOWNERS
.github/pull_request_template.md

- Adding CODEOWNERS file with same content as other repositories
- Adding pull request template with more focus on frontend

chore: adds CODEOWNERS and pull request template

---

src/components/layout/login.vue
src/store/accounts/actions.js

Fixes #12 
Hide/disable buttons that require user to be logged in
-  Removed error message
Try to log in to the login page, then close the anchor window and there should be no error message.

replace PR to new rep

---

.gitignore
public/statics/app-icons/back.svg
src/mixins/utils.js
src/pages/trails/ballots/view/ballot-view.vue
src/statics/app-icons/back-active.svg
src/statics/app-icons/back.svg
src/store/trails/actions.js

Fixes #14
For both in progress and completed ballots, we should show which accounts voted and what their vote was, as well as their vote weight. The vote weight we should maybe show as a % of the total. So if one account voted with 100 vote weight and there are 1000 total tokens that have voted, we'd show 10%.
-   Create layout for info in ballot card
-   Create info container for percents
Go to ballot card

merge form old repo

---

src/layouts/main.vue
src/store/accounts/actions.js

Fixes #25
refreshing after log in logs out
-   Create some action for check
-   call this action in main-layout
Steps to reproduce the behavior:
1.login via Anchor
2.refresh page
3.see logged out status

create ware for auth user

---

package.json
quasar.config.js
src/boot/api.js
src/boot/ual.js
src/store/accounts/actions.js
src/store/accounts/getters.js
src/store/accounts/mutations.js
src/store/accounts/state.js
yarn.lock

Fixes #43 
CleosAuthenticator was added as a new login option.
- @telosnetwork/ual-cleos was added in package.js
- added de Dialog plugin to quasar.config
- I modified the store accounts, adding the user concept with its mutations and actions. 
- CleosAuthenticator was added to ual.js authenticators list with two handlers (loginHandler, signHandler) taken and adapted from [this PR](https://github.com/telosnetwork/open-block-explorer/pull/263/files#diff-a77c8626639de1c2723fc4fb6838e2224b08407b313eb2473a8fe62ea7c1f91b).
I made a collage of several screenshots. 
I tested it manually.

Adding ual-cleos login

---

src/pages/index.vue

Fixes #8 #7 #5 
Remove links
Remove links from main page

remove links

---

src/components/layout/RightMenuAuthenticated.vue

removing Edit Profile option

---

src/components/ActionBar.vue
src/i18n/en-us/index.js
src/pages/trails/ballots/components/BallotForm.vue

Fixes and closes #77.
Removing leaderboard and election types of ballots.

Removing leaderboard and election types of ballots.

---

src/pages/trails/ballots/components/BallotListItem.vue
src/pages/trails/ballots/view/BallotView.vue

ballots vote percentage now displays with 2 decimals max

---

src/pages/trails/ballots/list/BallotsList.vue
src/store/trails/actions.js

Fixes #66
Include a summary of your changes.
-  Edit conditions 
-  Code Review

fix confitions for check status

---

src/boot/api.js
src/store/accounts/actions.js

Fixes #46
- Now memoryAutoLogin calls autoLogin when the user is not logged
- On logout localStorage now remove Item "account" which forgets the logged user (otherwise the user keeps logged if the page is refreshed)

fix: now after autoLogin user can actually sign transactions

---

src/pages/trails/ballots/view/BallotView.vue

This branch and commit were created because a conflict was found correctly by @karynemayer in the review of the [PR 91](https://github.com/telosnetwork/app-telos-native/pull/91) and I didn't know exactly how to solve it using git commands, so I created a brand new branch from the last commit from develop and push a correction in a single commit.
Fixes #90
The parsing was surrounded by try-catch and more possible structures were taken into account to extract valid URLs.
This replaces the [PR 91](https://github.com/telosnetwork/app-telos-native/pull/91)

iframeUrl function fixes issue #90

---

src/pages/trails/ballots/list/BallotsList.vue

Fixes #97 
Treasury filter is not working for treasuries that are not VOTE and other
-   Replace call func
-   Set default treasury
Change filters and other config for ballot list

fix treasury filtering not filtering treasuries

---

src/components/layout/HeaderMenu.vue
src/components/layout/LeftMenu.vue
src/i18n/en-us/index.js

This commit closes #76.
All links to other pages than the ballot were removed as described in #76.

Removing all non-working stuff links from header menu.

---

src/components/ActionBar.vue
src/i18n/en-us/index.js

Fixes #101 #102
Include a summary of your changes.
-   Change text
-   Remove (comment) btn for creating poll

remove btn and change text

---

src/components/ActionBar.vue
src/components/layout/HeaderMenu.vue
src/i18n/en-us/index.js
src/pages/trails/ballots/list/BallotsList.vue
src/router/routes.js

Fixes #94 #107 
Create Election page
-   Add new page
-   Create more dynamical login for this
-   Upgrade loader 
-   Upgrade watcher
You must visit this page and use it

add election page

---

src/components/ActionBar.vue
src/components/layout/HeaderMenu.vue
src/i18n/en-us/index.js
src/pages/trails/ballots/list/BallotsList.vue
src/router/routes.js

Reverts telosnetwork/app-telos-native#110
I'm proposing to revert this for now due to our time constraint.
We have identified as the cause for this #119, as per [Viter's comment](https://github.com/telosnetwork/app-telos-native/commit/4adfcb385087c6f5cc3a74f54731eb6b86fc7156#r84769480)

Revert "add election page"

---

src/components/ActionBar.vue

This is a temporal solution to avoid console errors. The definitive solution will come with the solution for #92 
Fixes #120

uncommented the button and hide it using stylesheet

---

src/pages/trails/ballots/list/BallotsList.vue

Displays a filter field for types
-   Add condition
-   Change number 2
-   Change number 3
Add screenshots that show your changes

fix conditions

---

src/pages/trails/ballots/list/BallotsList.vue

Fix filters and list after redirects from ballots to elections
-   Add rerender
-   Add condition
- 

fix lifters

---

src/components/ActionBar.vue
src/pages/trails/ballots/components/BallotForm.vue
src/pages/trails/ballots/components/BallotListItem.vue
src/pages/trails/ballots/list/BallotsList.vue
src/pages/trails/ballots/view/BallotView.vue
src/pages/trails/treasuries/components/AddVoterDialog.vue
src/pages/trails/treasuries/list/TreasuriesList.vue
src/store/trails/actions.js
src/store/trails/getters.js
src/store/trails/mutations.js
src/store/trails/state.js

This is a bunch of fixes to enhance the voting experience
Fixes #136

136 enhance voting experience

---

src/boot/ual.js
src/pages/trails/ballots/components/BallotForm.vue
src/pages/trails/ballots/view/BallotView.vue
src/store/accounts/actions.js
src/store/trails/actions.js

Fixes #137
This need to be tested in mobile using Anchor Authenticator.

fixed forced autologin with cleos

---

src/store/trails/mutations.js

Active ballots that are about to expire are shown first.
Fixes #157

Active ballots that are about to expire are shown first.

---

package.json
src/boot/ual.js

Updating ual-cleos version

---

src/pages/profiles/ProfileAvatar.vue
src/pages/profiles/read/ProfileDetail.vue
src/store/profiles/actions.js

Fixes #140 
Include a summary of your changes.
-   Add conditions 
Add screenshots that show your changes
Go to path Profile and make some edits with them

return profile info

---

src/boot/api.js

Fixes #130 
Fixed notification format for canceled transactions
-   Add conditions for check msg.details
-   Catch message from response
Cancel some transaction for test it

fix msg format

---

src/pages/trails/ballots/view/BallotView.vue

Proposal Modal not refreshing after successful vote. Need to refresh, so voted flag and updated results are shown.
- Call action update info for votes
Compare info before and after vote, u can see updated info

fix updates

---

package.json
yarn.lock

chore: bump ual-cleos version

---

.eslintrc.js
src/components/layout/RightMenuAuthenticated.vue
src/store/profiles/actions.js

update header profile icon on save profile pic upload
login, select my profile from drop-down
click the edit button.
upload a new profile image
click save
see updates 

fix edit profile response

---

src/components/ActionBar.vue
src/css/app.sass
src/css/quasar.variables.sass
src/i18n/en-us/index.js
src/mixins/validation.js
src/pages/trails/ballots/components/BallotForm.vue
src/pages/trails/ballots/list/BallotsList.vue
src/store/trails/actions.js

We need an easy and user-friendly way to create polls. For that, a wizard was created to replace the old ballot creation form. This PR implements most of the functionality for that component. Only remains better wording and responsive behavior.

new create ballot form using Stepper

---

src/components/ActionBar.vue
src/css/app.sass
src/css/quasar.variables.sass
src/i18n/en-us/index.js
src/mixins/validation.js
src/pages/trails/ballots/components/BallotForm.vue
src/pages/trails/ballots/list/BallotsList.vue
src/store/trails/actions.js

We need to momentously force new ballots to open for voting immediately. This is a temporary solution until we solve #209 completely.

210 all proposals start to be voted on when they are created

---

src/css/app.sass
src/pages/trails/ballots/components/BallotForm.vue
src/pages/trails/ballots/components/BallotOpenVotingDialog.vue

The current implementation of the wizard for ballot creation was not complete. This PR implements the responsive behavior to fit every possible screen resolution.

ballot creation wizard now is responsive

---

src/pages/trails/ballots/list/BallotsList.vue

Canceled ballots were shown when only active ballots are allowed by the filter in the ActionBar component. 
All the ballot filtering function was reimplemented for a much cleaner code. It takes care of this particular case.

Ballot filtering reimplemented

---

src/i18n/en-us/index.js
src/pages/trails/ballots/components/BallotForm.vue
src/pages/trails/ballots/view/BallotView.vue
src/store/trails/actions.js

I changed the way I was comparing two date times. The problem was that one of them was a string!!! (this only happens on js, typescript rules!). Fixed that and other several minor fixes.
- I created a new [ballot](https://deploy-preview-243--telos-app-native-staging.netlify.app/trails/ballot/kittycatball/1668552219588) not opened for voting. In this case, the ballot view dialog opened immediately after but the ballot was not listed. That was because the filter only included the active ones.
- I created a new [ballot](https://deploy-preview-243--telos-app-native-staging.netlify.app/trails/ballot/anotherkitty/1668552291762) opened for voting. In this case, the ballot view dialog opened right after and a few seconds later the ballot was listed as active and ready for voting.
-   [x] I have …

bugfix on date time comparison

---

src/components/ActionBar.vue
src/i18n/en-us/index.js
src/pages/trails/ballots/components/BallotForm.vue

This PR only updates some texts for better wording. The text change detail can be found in the issue #237.

 better wording on a list of points

---

src/components/layout/LeftMenu.vue
src/layouts/AuthLayout.vue

Once there was this LeftMenu component that was populating the left side layout drawer but was taken away temporally until now. It was adapted to fit best the current situation of the project navigation.

adding back the LeftMenu component for mobile resolutions

---

src/components/ActionBar.vue
src/components/CustomButton.vue
src/i18n/en-us/index.js
src/pages/trails/ballots/components/BallotForm.vue

The "create a proposal" button breaks everything in mid-term resolutions. So, in this range of widths from (`601px` until `820px`) instead of the normal button, we show a floating button instead.

making ActionBar more responsive

---

src/components/ActionBar.vue

Some of the rules written in the style section of the ActionBar component were making conflicts in other parts of the site, so it was changed from global to scoped to avoid these collateral effects. Since we have the policy of making every style block global, I adapted the code.

changing ActionBar style from scoped to global

---

src/i18n/en-us/index.js
src/pages/trails/ballots/components/BallotForm.vue
src/pages/trails/ballots/list/BallotsList.vue

While creating a ballot the user may decide to cancel the process and come back later. If the user leaves the form now he or she is asked whether to save the draft or discard the changes.

saving ballot creation state and recover from localStore

---

src/pages/resolve/util/case.ts

fix: update endpoint

---

src/pages/trails/ballots/view/BallotView.vue

This addresses both issues with the following changes: 
- Includes voters results to the mobile version
- Moves the `fetchVotesForBallot` call to `mounted` to be always available
- Includes bottom margin that mitigates the lack of visibility on mobile (`-webkit` specific css did not address the issue and the bottom margin gives some breathing space)
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] …

Includes voters result to mobile

---

src/pages/trails/ballots/view/BallotView.vue

Sort and space the options

---

src/layouts/AuthLayout.vue
src/pages/resolve/pages/case-file/CaseFileAction.vue
src/pages/trails/ballots/components/BallotForm.vue
src/pages/trails/ballots/components/BallotOpenVotingDialog.vue
src/pages/trails/ballots/list/BallotsList.vue

Redirect landing page during active election

---

src/boot/layouts.js
src/i18n/en-us/index.js
src/layouts/LogoLayout.vue
src/pages/testnet/TestnetEvmFaucet.vue
src/router/routes.js

See issue
See issue
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

feat: testnet faucet for evm only

---

src/pages/testnet/DevelopersPage.vue
src/store/testnet/actions.js

- using wrong network to check for account name availability in testnet account creation form
- 'negative' notification on successful account creation

fix testnet account availability check
