telosnetwork/app-telos-native

src/pages/trails/ballots/components/ballot-form.vue

Fixes #48 
When creating a new poll, the treasury that my account is registered to does not appear on the list.
Add init-call for treasuries
-Make sure you're registered in at least one group
-Go to the ballots page
-Click on create new ballot
-Click on treasury
-See that no treasury is listed

fix treasury-list for user

---

src/components/ActionBar.vue
src/pages/trails/ballots/components/BallotForm.vue

just avoid crashes by asserting the objects are not null and surrounding with try-catch some sensitive code.
Fixes #90

avoid crashes due to null objects property access attempts

---

src/components/ActionBar.vue

Fixes #132
Filter buttons are hidden on smaller screens
-   Change max-width for block
-   Remove gradient
Resize your screen

fix markup

---

package.json
src/store/accounts/actions.js

Without this fix, it was happening that if you log in with cleos, then log out and log in again, it never asked for the account name and permission. Instead, it goes directly to logged state with `null` as the account name.
Fixes #176

Fixing a bug related to cleos login

---

src/css/quasar.variables.sass
src/pages/trails/ballots/components/BallotChip.vue
src/pages/trails/ballots/components/BallotListItem.vue

Making all voted ballots to be visually consistent. 
Fixes #163
The current orange sign was not consistent with the green chip shown when the ballot is open. 
- Removing the big orange "Voted!"
- Adding a simple top-left green chip
- Adding a new color "ended" `#F7F7F7`

adding green-chip to voted ballots

---

src/boot/ual.js
src/store/accounts/actions.js

The previous solution works only in local (non-compressed code) deploys. The problem was that a decision was taken based only on the name of the authenticator constructor. This name (like most of the names) is replaced by a single-letter name and that breaks the solution based on names.
The new solution instead of asking for the authenticator's name, asks if the current authenticator is an instance of CleosAuthenticator class. So this solution should work also when deployed with compressed code.

CleosAuthenticator autologin definitive patch

---

src/components/ActionBar.vue
src/css/app.sass
src/css/quasar.variables.sass
src/i18n/en-us/index.js
src/mixins/validation.js
src/pages/trails/ballots/components/BallotForm.vue
src/pages/trails/ballots/components/BallotListItem.vue
src/pages/trails/ballots/components/BallotOpenVotingDialog.vue
src/pages/trails/ballots/components/BallotStatus.vue
src/pages/trails/ballots/list/BallotsList.vue
src/pages/trails/ballots/view/BallotView.vue
src/store/trails/actions.js
src/store/trails/getters.js
src/store/trails/mutations.js
src/store/trails/state.js

This PR contains a solution for storing and displaying ballot metadata following the new standard [DCMS-v2](https://github.com/telosnetwork/telos-decide/blob/master/dcms-v2.md) while keeping support for old ballot versions. Also reflects the not-opened ballot state in all components.
- ballots store now processes the content metadata following [DCMS-v2](https://github.com/telosnetwork/telos-decide/blob/master/dcms-v2.md) and make it ready to use everywhere.
- Ballot viewers component now extracts image, pdf, and options' metadata directly from the ballot object (no JSON process involved)
- The non-opened status for ballots is reflected in all ballot viewers
- The open ballot button is shown only for the creator

display new metadata for ballots and support for the non-opened state

---

src/pages/trails/ballots/list/BallotsList.vue
src/store/trails/actions.js
src/store/trails/mutations.js
src/store/trails/state.js

Not-started ballots were not shown using the `not started` filter from the ActionBar. 
- adjusted the way we identify a not started ballot (`ballot.type == 'setup'`)
- the query had to be changed to specifically ask for status == 'setup' because the start time was not set and that send the ballot to the last index by date.

changing how we query not-started ballots

---

src/css/quasar.variables.sass
src/i18n/en-us/index.js
src/pages/trails/treasuries/components/TreasuryCard.vue
src/pages/trails/treasuries/components/TreasuryForm.vue
src/pages/trails/treasuries/components/TreasuryTokenEditDialog.vue
src/pages/trails/treasuries/components/TreasuryTokenSettingsEdit.vue
src/store/trails/actions.js
src/store/trails/mutations.js

Since the DAO token is the main source of voting power it is essential to be able to at least transfer the tokens between voters in order to vote. But this functionality, among others, is disabled by default. So this PR includes the best initial configuration default for new DAOS and also provides two new ways of changing that configuration:
- 1. in the creation process there's a new field showing the tokens configuration and a button to open a dialog for the edition
- 2. Once the DAO is created, the manager can edit the token configuration by clicking on the new button on the DAO card header to open the same edition dialog.

UI for managing DAO token features

---

src/pages/trails/ballots/components/BallotForm.vue

All the components are prepared to handle not opened ballots but the current wizard implementation still has disabled the option to not open the ballot immediately. This PR fixes that.

unlocking the creation of unopened ballots in BallotForm

---

src/pages/trails/ballots/list/BallotsList.vue

The cross icon in the filter buttons means "apply no filters" so all the ballots should be should. This specific situation was not handled by the new implementation (cleaner but with this little bug inside).
The case was properly taken care of and now it works.

bugfix on handling the filter list when is empty

---

src/pages/trails/ballots/list/BallotsList.vue

Navigating from the Elections and the Proposals pages back and forth did not update the ballot shown. This PR fixes that.

refreshing the ballot list if routes changes

---

src/i18n/en-us/index.js
src/pages/trails/ballots/list/BallotsList.vue
src/pages/trails/treasuries/list/TreasuriesList.vue

The "Create a DAO" button was changed to fit the requirements mentioned [here](https://github.com/telosnetwork/app-telos-native/pull/248#issuecomment-1317960807).
The button does not show if the user is not logged in.

Changing the create a DAO button to top-right, scrolling with the page

---

src/pages/trails/ballots/view/BallotView.vue

The current size of the popup displaying the ballot was not using its full capacity. This PR expands a little more the popup size so it uses more available space.

making the ballot view popup fill the screen

---

src/i18n/en-us/index.js
src/pages/accounts/add/CongratulationsPage.vue

The button "Take to my account" was just redirecting to home and the text did not match the action. Now the button says "sign in" and actually redirects the user to the signing page.

changing the button "take me to my profile" to "sign in"

---

src/components/layout/HeaderMenu.vue

- 'Resolve' option available on [mainnet deploy preview link](https://deploy-preview-270--telos-app-native-mainnet.netlify.app/), functionality options consistent with testnet
-   [x] I have included all english text to the translation file
-   [x] I have created a new issue with the required translations for the currently supported languages

fix: enable arbitration portal for mainnet

---

src/i18n/en-us/index.js
src/pages/trails/ballots/view/BallotView.vue

Changes were made in order for the behavior to be the following:
- User is notified when multiple selection is available with a message including min and max number of options
- If user selects more than the max, we unselect the first selected item
- Changed scrolling to be enables at the popup level instead of the number of options so the user can see the item being unselected when he exceeds the maximum allowed
- Vote button and selections are disabled when not signed in.
use `/trails/ballot/myproposal/1683755639862` for testing
-   [ ] Any dependent …

[Closes #284 ] Adds max options logic

---

src/i18n/en-us/index.js

Cancel button not showing all text #267
It was a typo error

Cancel button not showing all text #267

---

src/pages/testnet/DevelopersPage.vue

Validate faucet inputs

---

src/pages/trails/ballots/view/BallotView.vue

- https://deploy-preview-347--telos-app-native-mainnet.netlify.app/trails/ballot/tsdp/1715263015597
- https://deploy-preview-347--telos-app-native-mainnet.netlify.app/trails/ballot/evmtokencrea/1715263605191
- https://deploy-preview-347--telos-app-native-mainnet.netlify.app/trails/ballot/antelopexibc/1715263625555

try to extract list of links from description

---

src/i18n/en-us/index.js
src/pages/testnet/DevelopersPage.vue
src/store/testnet/actions.js

A new tab was added to the dev tools page with a zkEVM faucet. Any developer can enter a valid address to receive up to 50 zTLOS daily with this faucet.
https://deploy-preview-351--telos-app-native-staging.netlify.app/testnet/developers?tab=tlos-zkevm

#350 | adding zkEVM faucet in dev-tools page
